
root_dir: C:\\Users\\xinyi\\Documents
train:
  net_type: sep_dir
  epochs: 100
  use_cuda: True
  img_height: 512
  img_width: 512
  batch_size: 1
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 4
  test_ratio: 0.15

  save_dir: try_38_2789

infer:
  mode: test
  infer_type: pick
  use_cuda: True
  batch_size: 1
  img_height: 512
  img_width: 512
