train:
  net_type: pick 
  epochs: 100
  use_cuda: True
  img_height: 512
  img_width: 512
  loss: mse
  batch_size: 2
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 0
  test_ratio: 0.10

  dataset: picknet_dataset
  save_folder: picknet_ckpt_try_0 
