infer:
  net_type: auto # pick, pull, auto
  mode: test
  use_cuda: True
  batch_size: 1
  img_height: 512
  img_width: 512
  pick_ckpt_folder: [picknet_ckpt, model_epoch_10.pth]
  pull_ckpt_folder: [pullnet_ckpt, model_epoch_21.pth]
