root_dir_win: C:\\Users\\xinyi\\Documents
root_dir_linux: /home/hlab/Documents

train:
  net_type: sep_dir
  backbone: resnet50
  epochs: 100
  use_cuda: True
  img_height: 512
  img_width: 512
  batch_size: 5 
  learning_rate: 0.0005
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 4
  test_ratio: 0.15

  dataset: SepDataAllPullVectorEight
  save_folder: try_sepnet_d_vector_eight_all

infer:
  infer_type: sep_dir 
  mode: test
  use_cuda: True
  batch_size: 1
  img_height: 512
  img_width: 512
  # pick_ckpt_folder: [try0, model_epoch_19.pth]
  pick_ckpt_folder: [try8,model_epoch_8.pth]
  # pick_ckpt_folder: [try_retrain_picknet_unet, model_epoch_25.pth]
  # sepp_ckpt_folder: [try_38,model_epoch_4.pth]
  sepp_ckpt_folder: [try_new_sepnet_position,model_epoch_5.pth]
  sepd_ckpt_folder: [try_new_res,model_epoch_12.pth]
