root_dir_win: C:\\Users\\xinyi\\Documents
root_dir_linux: /home/hlab/Documents

train:
  net_type: sep
  backbone: resnet34
  epochs: 100
  use_cuda: True
  img_height: 512
  img_width: 512
  loss: bce
  batch_size: 2 
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 0
  test_ratio: 0.15

  # dataset: PickDataNew 
  dataset: SepDataNew
  save_folder: try_sep_gauss2d

infer:
  net_type: pick_sep
  mode: test
  use_cuda: True
  batch_size: 1
  img_height: 512
  img_width: 512
  pick_ckpt_folder: [ckpt_picknet, model_epoch_8.pth]
  sep_ckpt_folder: [try_only_pull_action_map, model_epoch_20.pth]
  sep_ckpt_folder: [try_sep, model_epoch_20.pth]

validate:
  net: sep_pull
  use_cuda: True
  img_height: 512
  img_width: 512
  pick_data_folder: Nothing
  sep_data_folder: SepDataAllPullVectorVal
  pick_ckpt_folder: try8
  sepp_ckpt_folder: try_refine
  # sepd_ckpt_folder_v: try_SR
  # sepd_ckpt_folder_v: try_vector_augment_real 
  sepd_ckpt_folder_v: try_sepnet_vector_eight
  sepd_ckpt_folder_s: try_action_map_augment_real