root_dir_win: C:\\Users\\xinyi\\Documents
root_dir_linux: /home/hlab/Documents

train:
  net_type: pick
  backbone: resnet50
  epochs: 100
  use_cuda: True
  img_height: 512
  img_width: 512
  loss: mse
  batch_size: 2
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 0
  test_ratio: 0.15

  dataset: picknet_dataset
  save_folder: try_pick

infer:
  net_type: auto
  mode: test
  use_cuda: True
  batch_size: 1
  img_height: 512
  img_width: 512
  pick_ckpt_folder: [try_pick, model_epoch_10.pth]
  pull_ckpt_folder: [ckpt_pullnet, model_epoch_40.pth]
